## 1. Importing numpy

The syntax for importing most libraries is:
'import library as alias'.
As seen below;

In [6]:
import numpy as np

### 2. Importing modules from numpy

Syntax:
from library import module_name as alias

In [4]:
from numpy import random

### 3. Making numpy lists

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


### 4. 1D Lists

1D Lists contain a series of objects, like the one above

### 5. Indexing 1D Lists 

Indexing one element:

In [ ]:
print(a[0])

1


Indexing two elements:
    This is only possible for numpy ndarrays

In [15]:
print(a[[0, 1]])

[1 2]


Changing the shape of the Indexed Elements to (2,1)

In [19]:
print(a[[[0], [1]]])

[[1]
 [2]]


You can check the shape of the printed or stored array using the shape method

In [20]:
shape_method_eg = a[[[1], [3]]].shape
print(shape_method_eg)

(2, 1)


### 6. 1D Slicing

You can slice an array using slices with syntax list[start:end:step]

In [22]:
slice_eg = a[1:3]
print(slice_eg)

[2 3]


In [25]:
slice_eg = a[0:5:2]
print(slice_eg)

[1 3 5]


### 7. Boolean Indexing

In this, an array containing Trues and Falses is made, then it is aligned with another array, and the elements that are aligned with True get printed, those aligned with False are not printed

In [26]:
booleans = [True, False, True, False, True]
print(a[booleans])

[1 3 5]


### 8. 2D Arrays

These contain two lists, where each list correspond as rows when put in tabular form

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### 9. 2D Lists Indexing

In [9]:
print(b[0, 2])

3


This retrieves the rows with the specified indexes:

In [11]:
print(b[[1, 3]])

[[ 4  5  6]
 [10 11 12]]


This retrieves the rows specified in the first square brackets and the columns specified in the second square brackets:

In [13]:
print(b[[2, 4], [1,2]])

[ 8 15]


This prints all rows and the specified columns:

In [16]:
print(b[:, [1,2]])

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]]
