### 1. Importing numpy

The syntax for importing most libraries is:
'import library as alias'.
As seen below;

In [1]:
import numpy as np

### 2. Importing modules from numpy

Syntax:
from library import module_name as alias

In [2]:
from numpy import random

### 3. Making numpy lists

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


### 4. 1D Lists

1D Lists contain a series of objects, like the one above

### 5. Indexing 1D Lists 

Indexing one element:

In [4]:
print(a[0])

1


Indexing two elements:
    This is only possible for numpy ndarrays

In [5]:
print(a[[0, 1]])

[1 2]


Changing the shape of the Indexed Elements to (2,1)

In [6]:
print(a[[[0], [1]]])

[[1]
 [2]]


You can check the shape of the printed or stored array using the shape method

In [7]:
shape_method_eg = a[[[1], [3]]].shape
print(shape_method_eg)

(2, 1)


### 6. 1D Slicing

You can slice an array using slices with syntax list[start:end:step]

In [8]:
slice_eg = a[1:3]
print(slice_eg)

[2 3]


In [9]:
slice_eg = a[0:5:2]
print(slice_eg)

[1 3 5]


### 7. Boolean Indexing

In this, an array containing Trues and Falses is made, then it is aligned with another array, and the elements that are aligned with True get printed, those aligned with False are not printed

In [10]:
booleans = [True, False, True, False, True]
print(a[booleans])

[1 3 5]


### 8. 2D Arrays

These contain two lists, where each list correspond as rows when put in tabular form

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### 9. 2D Lists Indexing

In [12]:
print(b[0, 2])

3


This retrieves the rows with the specified indexes:

In [13]:
print(b[[1, 3]])

[[ 4  5  6]
 [10 11 12]]


This retrieves the rows specified in the first square brackets and the columns specified in the second square brackets:

In [14]:
print(b[[2, 4], [1,2]])

[ 8 15]


This prints all rows and the specified columns:

In [15]:
print(b[:, [1,2]])

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]]


In [16]:
print(b[:2, [0,1]])

[[1 2]
 [4 5]]


In [17]:
print(b[[0,1], :])

[[1 2 3]
 [4 5 6]]


In [18]:
print(b[[0, 2], 1])

[2 8]


This returns four values since the indexes specified in the first square brackets are mapped to each of the indexes specified in the second set of indexes:

In [19]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(b[[[1], [2]], [0, 2]])

[[4 6]
 [7 9]]


This also returns four values since the indexes specified in the second square brackets are mapped to each of the indexes in the first set of indexes:

In [20]:
print(b[[1, 2], [[0], [2]]])

[[4 7]
 [6 9]]


This returns only two values but with the shape of (2, 1)

In [21]:
print(b[[[1], [2]], [[0], [2]]].shape)

(2, 1)


### 10. 2D lists slicing

Specifying one block of indexes brings the rows corresponding to those indexes

In [22]:
print(b[1:4])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Specifying two blocks of indexes brings the indexes of rows and columns respectively:

In [23]:
print(b[0:3, 1:2])

[[2]
 [5]
 [8]]


You can also use negative indexing:

In [24]:
print(b[1:3, -3:-1])

[[4 5]
 [7 8]]


You can mix slicing and indexing:

In [25]:
print(b[:3, [1, 2]])

[[2 3]
 [5 6]
 [8 9]]


### 11. Boolean indexing

You can use boolean indexing by making a condition, that will create a list of booleans, then align it with the array you want to use it withy(usually the array you used to make the boolean condition in the first place.), the values that align with false, dont get stored in a variable nor printed

In [26]:
condition = (b % 2) != 1
print(b[condition])

[ 2  4  6  8 10 12 14]


In [43]:
print(b[condition][:3])

[2 4 6]


In [27]:
print(b[[[0],[1]], [True, False, True]])

[[1 3]
 [4 6]]


### 12. 2D Methods and Functions

Getting the minimum value of a list

In [28]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])

In [29]:
print(b.min())

1


Getting the maximum value of a list

In [30]:
print(b.max())

15


Getting the shape of a list

In [31]:
print(a.shape)
print(b.shape)

(5,)
(5, 3)


Getting the mean value (average) of a list

In [32]:
print(b.mean())

8.0


You can use the axis attribute to get the values such as min, max and mean from the horizontal or vertical axis

In [33]:
print(np.min(b, axis=1))

[ 1  4  7 10 13]


In [34]:
print(np.min(b, axis=0))

[1 2 3]


In [35]:
print(np.max(b, axis=1))

[ 3  6  9 12 15]


In [36]:
print(np.max(b, axis=0))

[13 14 15]


In [37]:
print(np.mean(b, axis=1))

[ 2.  5.  8. 11. 14.]


In [38]:
print(np.mean(b, axis=0))

[7. 8. 9.]


In [39]:
print(b.shape)

(5, 3)


You can change the number of rows and columns in a 2D array using the reshape method. To use the reshape method consider the number of elements in the array then look for numbers divisible by the total number of elements in the array.

In [40]:
print(len(b))

5


In [41]:
print(b.reshape(3, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Getting the Exponent of a list

In [42]:
print(np.exp(b))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]
 [4.42413392e+05 1.20260428e+06 3.26901737e+06]]


It is also possible to use python operators such as and(&), or(|) and not(~) operators where needed, forexample when appliying more than one condition in extracting specific data.